let obj = {
  "﻿FEATURE_ID": 479,
  FEATURE_NAME: "Adamana",
  FEATURE_CLASS: "Populated Place",
  CENSUS_CODE: 170,
  CENSUS_CLASS_CODE: "U6",
  GSA_CODE: null,
  OPM_CODE: null,
  STATE_NUMERIC: 4,
  STATE_ALPHA: "AZ",
  COUNTY_SEQUENCE: 1,
  COUNTY_NUMERIC: 1,
  COUNTY_NAME: "Apache",
  PRIMARY_LATITUDE: 34.9766921,
  PRIMARY_LONGITUDE: -109.8223383,
  DATE_CREATED: {
  },
  DATE_EDITED: null,
};
